### ISSUE TITLE
Segfault Across All Examples

### ISSUE THREAD

**Issue by pindapuj** [gdellapenna/UPMurphi#1] opened 2018-07-17 15:50 UTC
Hello! 
Thank you for making this planner available. I was testing it out on the example problems and all of them failed with Segmentation Fault  during the "Compiling Model" step. 

Below is the stack trace: 
`Start UPMurphi translation... 

 ----- CONFIG FILE ----- 
PDDL Domain File: /root/UPMurphi/ex/generator_linear/genlinear.pddl
PDDL Problem File: /root/UPMurphi/ex/generator_linear/genproblinear.pddl
The output model will be written on file: /root/UPMurphi/ex/generator_linear/genlinear.m
The output external function file will be written on file: /root/UPMurphi/ex/generator_linear/genlinear.h
 ----- DOMAIN SETTINGS ----- 
 Time discretisation: 1.000000
 Real number: (Integer): 5.000000 digits for the integer part
 Real number: (Fractional) 2.000000 digits for the fractional part

 ...Translation completed 

Errors: 0, warnings: 0
PDDL compilation successful, no errors
UPMurphi model generated in file /root/UPMurphi/ex/generator_linear/genlinear.m
Compiling model...
Segmentation fault
`
Thanks!

**Comment by gdellapenna** [comment] 2018-10-30 16:37
The latest libc and flex versions are incompatible with the UPMurphi core, which unfortunately uses legacy Murphi code. Currently UPMurphi has no dedicated maintainer, so we are able to update its (rather old) code only occasionally. Anyway, this issue should be now fixed, since we were able to compile UPMurphi and successfully run all the examples under Ubuntu 18.04 with gcc 7.3.0 (see TROUBLESHOOT.txt)

**Comment by gdellapenna** [comment] 2018-10-30 16:39
I can confirm that the issue was (at least temporarily) fixed by disabling optimizations (-O0) for the upmc executable and installing the tool/library versions listed in TROUBLESHOOT.txt

**Closed as completed by gdellapenna** 2018-10-30 16:39 UTC
